// <auto-generated />
using System;
using EkamArtMBProj.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EkamArtMBProj.Migrations
{
    [DbContext(typeof(PaintingDbContext))]
    [Migration("20210908094606_orderupdate")]
    partial class orderupdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("EkamArtMBProj.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Watercolor",
                            Description = "The most versatile and fresh medium"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Acrylic",
                            Description = "The most versatile and fresh medium"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Gouache",
                            Description = "The most versatile and fresh medium"
                        });
                });

            modelBuilder.Entity("EkamArtMBProj.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("OrderId");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("EkamArtMBProj.Models.Painting", b =>
                {
                    b.Property<int>("PaintingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CareInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaintingOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaintingId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Paintings");

                    b.HasData(
                        new
                        {
                            PaintingId = 1,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/images/Alley.jpg",
                            ImageUrl = "/images/Alley.jpg",
                            InStock = true,
                            IsPaintingOfTheWeek = false,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Diagon Alley",
                            Price = 15000m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PaintingId = 2,
                            CategoryId = 2,
                            ImageThumbnailUrl = "/images/saadhu.jpg",
                            ImageUrl = "/images/saadhu.jpg",
                            InStock = true,
                            IsPaintingOfTheWeek = false,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Portrait of a Sadhu",
                            Price = 10000m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PaintingId = 3,
                            CategoryId = 3,
                            ImageThumbnailUrl = "/images/Well.jpg",
                            ImageUrl = "/images/Well.jpg",
                            InStock = true,
                            IsPaintingOfTheWeek = false,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Stairway to Heaven",
                            Price = 20000m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PaintingId = 4,
                            CategoryId = 2,
                            ImageThumbnailUrl = "/images/Greece.jpg",
                            ImageUrl = "/images/Greece.jpg",
                            InStock = true,
                            IsPaintingOfTheWeek = true,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Greece Magic",
                            Price = 8500m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PaintingId = 5,
                            CategoryId = 2,
                            ImageThumbnailUrl = "/images/boat.jpeg",
                            ImageUrl = "/images/boat.jpeg",
                            InStock = true,
                            IsPaintingOfTheWeek = true,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Sunset Skies",
                            Price = 19500m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PaintingId = 6,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/images/Sunflowers.png",
                            ImageUrl = "/images/Sunflowers.png",
                            InStock = true,
                            IsPaintingOfTheWeek = true,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Sunriched",
                            Price = 12000m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PaintingId = 7,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/images/lotus3.png",
                            ImageUrl = "/images/lotus3.jpg",
                            InStock = true,
                            IsPaintingOfTheWeek = true,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Bloom",
                            Price = 12000m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PaintingId = 8,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/images/Lilly.jpg",
                            ImageUrl = "/images/Lilly.jpg",
                            InStock = true,
                            IsPaintingOfTheWeek = true,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Bloom again",
                            Price = 12000m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PaintingId = 9,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/images/peacock2.jpeg",
                            ImageUrl = "/images/peacock2.jpeg",
                            InStock = true,
                            IsPaintingOfTheWeek = false,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Blue Beauty",
                            Price = 12000m,
                            ShortDescription = "Lorem Ipsum"
                        });
                });

            modelBuilder.Entity("EkamArtMBProj.Models.Painting", b =>
                {
                    b.HasOne("EkamArtMBProj.Models.Category", "Category")
                        .WithMany("Paintings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EkamArtMBProj.Models.Category", b =>
                {
                    b.Navigation("Paintings");
                });
#pragma warning restore 612, 618
        }
    }
}
