// <auto-generated />
using EkamArtMBProj.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EkamArtMBProj.Migrations
{
    [DbContext(typeof(PaintingDbContext))]
    partial class PaintingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("EkamArtMBProj.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Watercolor",
                            Description = "The most versatile and fresh medium"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Acrylic",
                            Description = "The most versatile and fresh medium"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Gouache",
                            Description = "The most versatile and fresh medium"
                        });
                });

            modelBuilder.Entity("EkamArtMBProj.Models.Painting", b =>
                {
                    b.Property<int>("PaintingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("CareInformation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ImageThumbnailUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPaintingOfTheWeek")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaintingId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Paintings");

                    b.HasData(
                        new
                        {
                            PaintingId = 1,
                            CategoryId = 1,
                            ImageThumbnailUrl = "/images/Alley.jpg",
                            ImageUrl = "/images/Alley.jpg",
                            InStock = true,
                            IsPaintingOfTheWeek = false,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Diagon Alley",
                            Price = 15000m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PaintingId = 2,
                            CategoryId = 2,
                            ImageThumbnailUrl = "/images/saadhu.jpg",
                            ImageUrl = "/images/saadhu.jpg",
                            InStock = true,
                            IsPaintingOfTheWeek = false,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Portrait of a Sadhu",
                            Price = 10000m,
                            ShortDescription = "Lorem Ipsum"
                        },
                        new
                        {
                            PaintingId = 3,
                            CategoryId = 3,
                            ImageThumbnailUrl = "/images/Well.jpg",
                            ImageUrl = "/images/Well.jpg",
                            InStock = true,
                            IsPaintingOfTheWeek = false,
                            LongDescription = "A Beautiful painting that can enhance your home space!",
                            Name = "Stairway to Heaven",
                            Price = 20000m,
                            ShortDescription = "Lorem Ipsum"
                        });
                });

            modelBuilder.Entity("EkamArtMBProj.Models.Painting", b =>
                {
                    b.HasOne("EkamArtMBProj.Models.Category", "Category")
                        .WithMany("Paintings")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EkamArtMBProj.Models.Category", b =>
                {
                    b.Navigation("Paintings");
                });
#pragma warning restore 612, 618
        }
    }
}
